### ISSUE TITLE
question : installed jekyll but couldn't launch

### ISSUE THREAD

**Issue by RIAEvangelist** [NetOperatorWibby/DSGN#2]
got the following error on ubuntu 14.04 don't know about ruby or jekyll, any help or suggestions would be appreciated.

~/git/DSGN$ jekyll serve --watch
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': iconv will be deprecated in the future, use String#encode instead.
/usr/bin/jekyll:137:in `<main>': invalid option: --watch (OptionParser::InvalidOption)

**Comment by NetOperatorWibby** [comment]
Hmm, I'm not sure what's going on. I created this repo while on Windows and now I'm on a Mac. I haven't experienced the issue you're dealing with, unfortunately. I believe that `iconv` message is just a warning, it shouldn't prevent the app from running.

I'm getting some new Raspberry Pis soon, I'll test this issue on them when they arrive.

**Comment by RIAEvangelist** [comment]
Getting closer figured I would run an apt-get update / upgrade since I just installed jekyll
got a bunch.
Still no luck, tried running without watch

got closer
needed to gem install rdiscount

but it fails :(

$ sudo gem install rdiscount --force
Building native extensions.  This could take a while...
ERROR:  Error installing rdiscount:
	ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from extconf.rb:1:in `<main>'


Gem files will remain installed in /var/lib/gems/1.9.1/gems/rdiscount-2.1.8 for inspection.
Results logged to /var/lib/gems/1.9.1/gems/rdiscount-2.1.8/ext/gem_make.out
bmiller@bmiller-Latitude-E7440:~/git/DSGN$ sudo gem install rdiscount
Building native extensions.  This could take a while...
ERROR:  Error installing rdiscount:
	ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from extconf.rb:1:in `<main>'


Gem files will remain installed in /var/lib/gems/1.9.1/gems/rdiscount-2.1.8 for inspection.
Results logged to /var/lib/gems/1.9.1/gems/rdiscount-2.1.8/ext/gem_make.out

**Comment by RIAEvangelist** [comment]
Anyway, saw this online i think. 

http://dsgn.io/ right?

very cool.

**Comment by NetOperatorWibby** [comment]
Yup. I was going to redesign it, but I'm going to hold off on that and do a "re-align" as well. Just improve the existing codebase and make the styling adjustments that's been bothering me.

**Comment by NetOperatorWibby** [comment]
Hey @RIAEvangelist, are you still having a build issue?

**Comment by RIAEvangelist** [comment]
Havent tried since last time. You make changes?

**Comment by NetOperatorWibby** [comment]
Yup, I updated Jekyll and changed my folder structures/dependecies.

On Mon, May 4, 2015 at 5:45 PM, NetOperatorWibby/DSGN
<reply@reply.github.com>
wrote:
Havent tried since last time. You make changes?

—
Reply to this email directly or view it on GitHub
[https://github.com/NetOperatorWibby/DSGN/issues/2#issuecomment-98857007] .[https://github.com/notifications/beacon/ABOopKLxLw3x2Ki0nytJVGyLP7qIGWI4ks5oF-AUgaJpZM4DcAao.gif]

**Comment by RIAEvangelist** [comment]
OK, I'll give it a shot this week.
