### ISSUE TITLE
.ugh doesn't keep up with scrolling

### ISSUE THREAD

**Issue by karelvuong** [NetOperatorWibby/DSGN#6]
Hey Paul, the site looks great! 

Just wanted to bring this to your attention: as you're scrolling down the page, the `<div class="ugh"></div> ` doesn't keep up with scrolling. It looks like you're setting the `top: n px` as the user scrolls down the page but depending on how quickly or slowly the user does, it bugs out and shows this: 

![screen shot 2015-03-08 at 4 25 41 pm](https://cloud.githubusercontent.com/assets/2213571/6548254/d1c3600e-c5af-11e4-8005-0db82e9cc66d.png)

Cheers! :clap:

**Comment by NetOperatorWibby** [comment]
Yeah, I noticed this myself @karelvuong, I'm going to fix this. Thanks for providing a screenshot though! I'm going to test this on my Windows laptop as well. I assume it's due to the smooth scrolling of Mac systems, but I could be wrong.

**Comment by NetOperatorWibby** [comment]
@karelvuong Are you still seeing this issue?

**Comment by NetOperatorWibby** [comment]
This is no longer an issue, due to awesome site redesign.
